### ISSUE TITLE
Guides version select

### ISSUE THREAD

**Issue by jenweber** [ember-learn/glimmer-styleguide#1]
We'll build a Glimmer component to replace the current select menu. It's a bit complicated as-is, so this is a good opportunity to start adding Glimmer to handle this functionality rather than refactor.

### To do
- [x] basic dropdown
- [x] replace select2 functionality
- [x] styling
- [x] web component renders in the guides
- [x] figure out custom events to pass info
- [x] utilize window.GUIDE_VERSIONS instead of internal versions.fetch
- [x] dropdown should be a layer that does not push other content down 
- [x] figure out a11y for the custom select behavior
- [ ] integrate with transition behavior in the guides
- [ ] write a function in the guides that replaces the activeVersion text
- [ ] emit loaded event? `window.GUIDE_VERSIONS.onReady` fires before the web component is loaded so I need something to trigger the jquery event handler registration
- [ ] refactor things I overcomplicated
- [ ] polyfill for web components

Open questions
- [x] where should styling ultimately live?
- [ ] is there a staging environment available to test the currentVersion functionality?

**Comment by jenweber** [comment]
@locks I'm not sure how to integrate this repo with the Guides, given the Ruby environment. Should I be researching adding JavaScript dependencies/web components to a middleman project? [Edit] So far I'm copying and pasting the build into the Guides, and now working on how to get the component to actually show up with something by hand like [this](https://www.webcomponents.org/community/articles/introduction-to-html-imports) or [this](https://www.html5rocks.com/en/tutorials/webcomponents/imports/).

Sidenote, in the Guides repo, it seems like we would also need to implement the polyfill for Web Components. This is based on the [Browser Support](https://github.com/glimmerjs/glimmer-web-component) section of the glimmer-web-component README.

**Comment by locks** [comment]
@jenweber that's basically what I did for development, too. We will need to figure out a proper way to deploy, probably something similar to the builds and the dashboard apps, we can discuss at the weekly meeting.

I think we just need to include the polyfill mentioned in the linked README section?

**Comment by jenweber** [comment]
Never mind, I completely misread a section of the guides about how to use the app as individual web components. [This video](https://www.youtube.com/watch?v=bj7LBjqrM3k) was helpful.

@locks ~~Did you manage to display a specific component? Right now I'm rendering the whole Glimmer app like this~~

**Comment by jenweber** [comment]
@locks What do you think should be the separation of concerns between the dropdown and the rest of the Guides website? I'm inclined to fire a custom event from the component that says a new version has been selected, and then let the guides catch it and handle what happens in response. In that case, I would access the window.GUIDE_VERSIONS and current_version objects and use them. Thoughts?

I'm going to try to wrap this up this week. Got slowed down by trying to replicate select2's accessibility and keyboard control stuff but it's mostly done.

**Comment by locks** [comment]
@jenweber for now the dropdown should do the transition, as it's more trouble than worth to wire up the glimmer component to some JavaScript of the guides to then do the transition.

**Comment by jenweber** [comment]
closed, any similar components will be done with ember-styleguide
